Add missing module dependencies
Add dependencies on modules 'mediawiki.api' and 'mediawiki.user'.

This change prevents the error
> Uncaught TypeError: mw.user.isNamed is not a function
when loading this extension with debug mode.

Change-Id: I12cb544dc91cc339781b6a31a4a699a4fa023a9b